// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

using System.ComponentModel.DataAnnotations;

namespace Tailstale.Models
{
    public class Sbusiness_imgViewModel
    {

        public int ID { get; set; }

        public int? img_type_id { get; set; }

        public string URL { get; set; }

        [Required(ErrorMessage = "name欄位未填寫")]
        public string name { get; set; }

        public DateTime? created_at { get; set; }

        public virtual business_img_type img_type { get; set; }

        //public virtual ICollection<vet_Information> vet_informations { get; set; } = new List<vet_Information>();

    }
}
