// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class article
{
    public int ID { get; set; }

    public int? FK_Keeper_ID { get; set; }

    public int? parent_ID { get; set; }

    public string content { get; set; }

    public bool? ispublic { get; set; }

    public DateTime? created_at { get; set; }

    public virtual keeper FK_Keeper { get; set; }

    public virtual ICollection<article> Inverseparent { get; set; } = new List<article>();

    public virtual article parent { get; set; }

    public virtual ICollection<using_person_tag> using_person_tags { get; set; } = new List<using_person_tag>();

    public virtual ICollection<using_tag> using_tags { get; set; } = new List<using_tag>();
}