// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelAPI.Models;

public partial class BookingDetail
{
    public int BdId { get; set; }

    public int? BookingId { get; set; }

    public int? RoomId { get; set; }

    public int? BdAmount { get; set; }

    public int? BdTotal { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Room Room { get; set; }
}