// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelAPI.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int? KeeperId { get; set; }

    public int? HotelId { get; set; }

    public DateTime? CheckinDate { get; set; }

    public DateTime? CheckoutDate { get; set; }

    public int? BookingAmountTotal { get; set; }

    public string BookingStatus { get; set; }

    public DateTime? BookingDate { get; set; }

    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    public virtual ICollection<CheckinDetail> CheckinDetails { get; set; } = new List<CheckinDetail>();

    public virtual Business Hotel { get; set; }

    public virtual Keeper Keeper { get; set; }

    public virtual ICollection<PaymentInfo> PaymentInfos { get; set; } = new List<PaymentInfo>();
}