// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelAPI.Models;

public partial class BusinessImgType
{
    public int Id { get; set; }

    public int? FkBusinessId { get; set; }

    public string Typename { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<BusinessImg> BusinessImgs { get; set; } = new List<BusinessImg>();

    public virtual Business FkBusiness { get; set; }
}