// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelAPI.Models;

public partial class BusinessImg
{
    public int Id { get; set; }

    public int? ImgTypeId { get; set; }

    public string Url { get; set; }

    public string Name { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual BusinessImgType ImgType { get; set; }
}