// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelAPI.Models;

public partial class BusinessType
{
    public int BusinessTypeId { get; set; }

    public string BusinessTypeName { get; set; }

    public virtual ICollection<Business> Businesses { get; set; } = new List<Business>();
}