// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelAPI.Models;

public partial class Business
{
    public int Id { get; set; }

    public string Password { get; set; }

    public int? TypeId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string GeoJson { get; set; }

    public string LicenseNumber { get; set; }

    public int FkStatusId { get; set; }

    public string PhotoUrl { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<BusinessHour> BusinessHours { get; set; } = new List<BusinessHour>();

    public virtual ICollection<BusinessImgType> BusinessImgTypes { get; set; } = new List<BusinessImgType>();

    public virtual ICollection<PaymentInfo> PaymentInfos { get; set; } = new List<PaymentInfo>();

    public virtual ICollection<Room> Rooms { get; set; } = new List<Room>();

    public virtual BusinessType Type { get; set; }
}