// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class Consumption_Record
{
    public int id { get; set; }

    public int keeper_id { get; set; }

    public string pet_name { get; set; }

    public int business_ID { get; set; }

    public DateTime time { get; set; }

    public int beautician_id { get; set; }

    public string service_name { get; set; }

    public decimal pet_weight { get; set; }

    public int price { get; set; }

    public DateTime? end_time { get; set; }

    public string before_photo { get; set; }

    public string after_photo { get; set; }

    public virtual Beautician beautician { get; set; }

    public virtual business business { get; set; }

    public virtual keeper keeper { get; set; }
}