// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class daily_outpatient_clinic_schedule
{
    public int daily_outpatient_clinic_schedule_ID { get; set; }

    public int? outpatient_clinic_ID { get; set; }

    public DateOnly? date { get; set; }

    public DateOnly? created_date { get; set; }

    public bool daily_outpatient_clinic_schedule_status { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual outpatient_clinic outpatient_clinic { get; set; }
}