// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelAPI.Models;

public partial class KeeperImgType
{
    public int Id { get; set; }

    public int? FkKeeperId { get; set; }

    public string Typename { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Keeper FkKeeper { get; set; }

    public virtual ICollection<KeeperImg> KeeperImgs { get; set; } = new List<KeeperImg>();
}