// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class medical_record
{
    public int id { get; set; }

    public int? keeper_id { get; set; }

    public int? pet_id { get; set; }

    public DateTime? created_at { get; set; }

    public int? outpatient_clinic_id { get; set; }

    public decimal? weight { get; set; }

    public int? vital_sign_record_id { get; set; }

    public string admission_process { get; set; }

    public string diagnosis { get; set; }

    public string treatment { get; set; }

    public string memo { get; set; }

    public int? fee { get; set; }

    public virtual ICollection<hosp_history> hosp_histories { get; set; } = new List<hosp_history>();

    public virtual keeper keeper { get; set; }

    public virtual outpatient_clinic outpatient_clinic { get; set; }

    public virtual pet pet { get; set; }

    public virtual ICollection<surgery> surgeries { get; set; } = new List<surgery>();

    public virtual vital_sign_record vital_sign_record { get; set; }
}