// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelAPI.Models;

public partial class OrderStatus
{
    public int Id { get; set; }

    public string StatusName { get; set; }
}