// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelAPI.Models;

public partial class PaymentInfo
{
    public int PaymentId { get; set; }

    public int? BusinessId { get; set; }

    public int? KeeperId { get; set; }

    public int? BookingId { get; set; }

    public string CardholderName { get; set; }

    public int? CardNumber { get; set; }

    public DateOnly? ExpirationDate { get; set; }

    public int? CvvNumber { get; set; }

    public int? PaymentAmount { get; set; }

    public byte[] PaymentStatus { get; set; }

    public DateTime? PaymentTimestamp { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Business Business { get; set; }

    public virtual Keeper Keeper { get; set; }
}