// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class pet_type
{
    public int ID { get; set; }

    public string species { get; set; }

    public string breed { get; set; }

    public virtual ICollection<pet> pets { get; set; } = new List<pet>();

    public virtual ICollection<speciman> specimen { get; set; } = new List<speciman>();
}