// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class record_type
{
    public int id { get; set; }

    public string name { get; set; }

    public virtual ICollection<image_file> image_files { get; set; } = new List<image_file>();
}