// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelAPI.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int? RoomId { get; set; }

    public int? KeeperId { get; set; }

    public int? ReviewRating { get; set; }

    public string ReviewText { get; set; }

    public DateTime? ReviewDate { get; set; }

    public virtual Keeper Keeper { get; set; }

    public virtual Room Room { get; set; }
}