// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelAPI.Models;

public partial class Room
{
    public int RoomId { get; set; }

    public int HotelId { get; set; }

    public string RoomSpecies { get; set; }

    public string RoomType { get; set; }

    public int? RoomPrice { get; set; }

    public int? RoomDiscount { get; set; }

    public int? RoomReserve { get; set; }

    public string RoomDescrep { get; set; }

    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    public virtual ICollection<CheckinDetail> CheckinDetails { get; set; } = new List<CheckinDetail>();

    public virtual Business Hotel { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}