// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class surgery
{
    public int id { get; set; }

    public DateTime start_time { get; set; }

    public int? medical_record_id { get; set; }

    public string technique { get; set; }

    public int? medicine_order_record { get; set; }

    public string anesthesia_duration { get; set; }

    public int? vital_sign_record_id { get; set; }

    public string findings { get; set; }

    public string op_duration { get; set; }

    public virtual medical_record medical_record { get; set; }

    public virtual medicine_order_record medicine_order_recordNavigation { get; set; }

    public virtual vital_sign_record vital_sign_record { get; set; }
}