// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class tag
{
    public int ID { get; set; }

    public string name { get; set; }

    public virtual ICollection<using_tag> using_tags { get; set; } = new List<using_tag>();
}