// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class ward
{
    public int ward_ID { get; set; }

    public string ward_name { get; set; }

    public int? business_ID { get; set; }

    public bool ward_status { get; set; }

    public string memo { get; set; }

    public virtual business business { get; set; }

    public virtual ICollection<hosp_history> hosp_histories { get; set; } = new List<hosp_history>();
}