// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class Appointment
{
    public int Appointment_ID { get; set; }

    public int? pet_ID { get; set; }

    public int? keeper_ID { get; set; }

    public DateTime? registration_time { get; set; }

    public int? outpatient_clinic_ID { get; set; }

    public int? status { get; set; }

    public virtual keeper keeper { get; set; }

    public virtual outpatient_clinic outpatient_clinic { get; set; }

    public virtual pet pet { get; set; }

    public virtual order_status statusNavigation { get; set; }
}