// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class Appointment
{
    public int Appointment_ID { get; set; }

    public int? pet_ID { get; set; }

    public int? keeper_ID { get; set; }

    public DateTime? registration_time { get; set; }

    public int? daily_outpatient_clinic_schedule_ID { get; set; }

    public int? Appointment_status { get; set; }

    public virtual order_status Appointment_statusNavigation { get; set; }

    public virtual daily_outpatient_clinic_schedule daily_outpatient_clinic_schedule { get; set; }

    public virtual keeper keeper { get; set; }

    public virtual pet pet { get; set; }
}