// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class article_img
{
    public int AI_ID { get; set; }

    public int FK_article_ID { get; set; }

    public int? FK_Keeper_img_ID { get; set; }

    public int? FK_Business_img_ID { get; set; }

    public virtual business_img FK_Business_img { get; set; }

    public virtual keeper_img FK_Keeper_img { get; set; }

    public virtual article FK_article { get; set; }
}