// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Tailstale.Models;

public partial class Beautician
{
    public int id { get; set; }

    public string name { get; set; }

    public string gender { get; set; }

    public string photo { get; set; }

    public string phone { get; set; }

    [Required(ErrorMessage = "business_ID欄位未填寫")]
    public int business_ID { get; set; }

    public string Highest_license { get; set; }

    public string Remark { get; set; }

    public virtual ICollection<Consumption_Record> Consumption_Records { get; set; } = new List<Consumption_Record>();

    public virtual business business { get; set; }
}