// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Tailstale.Models;

public partial class Beautician
{
    public int id { get; set; }

    [StringLength(maximumLength: 30, MinimumLength = 1, ErrorMessage = "長度不合法,最多30字")]//,最多8個字,最少3個字,可以防攻擊
    [Required(ErrorMessage = "name欄位未填寫")]
    public string name { get; set; }

    [StringLength(maximumLength: 1, ErrorMessage = "長度不合法,最多1字")]//,最多8個字,最少3個字,可以防攻擊
    [Required(ErrorMessage = "gender欄位未填寫")]
    public string gender { get; set; }

    public string photo { get; set; }

    [StringLength(maximumLength: 16, MinimumLength = 1, ErrorMessage = "長度不合法,最多16字")]//,最多8個字,最少3個字,可以防攻擊
    [Required(ErrorMessage = "phone欄位未填寫")]
    public string phone { get; set; }

    
    [Required(ErrorMessage = "business_ID欄位未填寫")]
    public int business_ID { get; set; }

    public string Highest_license { get; set; }

    public string Remark { get; set; }

    public virtual ICollection<Consumption_Record> Consumption_Record { get; set; } = new List<Consumption_Record>();

    public virtual business business { get; set; }
}