// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class biological_test
{
    public int id { get; set; }

    public int? pet_details_id { get; set; }

    public DateTime? created_at { get; set; }

    public int? specimen_id { get; set; }

    public int lab_data { get; set; }

    public string findings { get; set; }

    public virtual ICollection<medical_record> medical_records { get; set; } = new List<medical_record>();

    public virtual ICollection<nursing_record> nursing_records { get; set; } = new List<nursing_record>();

    public virtual pet pet_details { get; set; }

    public virtual speciman specimen { get; set; }
}