// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class biological_test
{
    public int id { get; set; }

    public DateTime? test_time { get; set; }

    public string test_name { get; set; }

    public decimal lab_data { get; set; }

    public string findings { get; set; }

    public int? specimen_id { get; set; }

    public int? biological_test_order_id { get; set; }

    public virtual biological_test_order biological_test_order { get; set; }

    public virtual speciman specimen { get; set; }
}