// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class biological_test_order
{
    public int id { get; set; }

    public DateTime? test_time { get; set; }

    public int? medical_orders_id { get; set; }

    public virtual ICollection<biological_test> biological_tests { get; set; } = new List<biological_test>();

    public virtual medical_order medical_orders { get; set; }
}