// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class biological_test_order
{
    public int id { get; set; }

<<<<<<<< HEAD:Tailstale/Models/biological_test.cs
    public DateTime? test_time { get; set; }

    public decimal lab_data { get; set; }

    public string findings { get; set; }

    public int? specimen_id { get; set; }

    public int? biological_test_order_id { get; set; }

    public virtual biological_test_order biological_test_order { get; set; }
========
    public DateTime order_time { get; set; }

    public DateTime test_time { get; set; }

    public int? specimen_id { get; set; }

    public int? medical_orders_id { get; set; }

    public virtual medical_order medical_orders { get; set; }
>>>>>>>> med-record,V2:Tailstale/Models/biological_test_order.cs

    public virtual speciman specimen { get; set; }
}