// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class Booking
{
    public int bookingID { get; set; }

    public int? keeper_ID { get; set; }

    public int? hotelID { get; set; }

    public DateTime? checkinDate { get; set; }

    public DateTime? checkoutDate { get; set; }

    public int? bookingAmountTotal { get; set; }

    public string bookingStatus { get; set; }

    public DateTime? bookingDate { get; set; }

    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    public virtual ICollection<CheckinDetail> CheckinDetails { get; set; } = new List<CheckinDetail>();

    public virtual ICollection<PaymentInfo> PaymentInfos { get; set; } = new List<PaymentInfo>();

    public virtual business hotel { get; set; }

    public virtual keeper keeper { get; set; }
}