// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class BookingDetail
{
    public int bdID { get; set; }

    public int? bookingID { get; set; }

    public int? roomID { get; set; }

    public int? bdAmount { get; set; }

    public int? bdTotal { get; set; }

    public virtual Booking booking { get; set; }

    public virtual Room room { get; set; }
}