// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class Business_hour
{
    public int id { get; set; }

    public int business_ID { get; set; }

    public DateOnly business_day { get; set; }

    public int people_limit { get; set; }

    public virtual business business { get; set; }
}