// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class business
{
    public int ID { get; set; }

    public string password { get; set; }

    public int? type_ID { get; set; }

    public string name { get; set; }

    public string email { get; set; }

    public string phone { get; set; }

    public string address { get; set; }

    public string geoJson { get; set; }

    public string license_number { get; set; }

    public int? FK_status_ID { get; set; }

    public string photo_url { get; set; }

    public DateTime? created_at { get; set; }

    public virtual ICollection<Beautician> Beauticians { get; set; } = new List<Beautician>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Business_hour> Business_hours { get; set; } = new List<Business_hour>();

    public virtual ICollection<Consumption_Record> Consumption_Records { get; set; } = new List<Consumption_Record>();

    public virtual status FK_status { get; set; }

    public virtual ICollection<PaymentInfo> PaymentInfos { get; set; } = new List<PaymentInfo>();

    public virtual ICollection<Reserve> Reserves { get; set; } = new List<Reserve>();

    public virtual ICollection<Room> Rooms { get; set; } = new List<Room>();

    public virtual ICollection<Service> Services { get; set; } = new List<Service>();

    public virtual ICollection<Store_Service> Store_Services { get; set; } = new List<Store_Service>();

    public virtual ICollection<business_img_type> business_img_types { get; set; } = new List<business_img_type>();

    public virtual ICollection<department> departments { get; set; } = new List<department>();

    public virtual ICollection<memo> memos { get; set; } = new List<memo>();

    public virtual ICollection<outpatient_clinic> outpatient_clinics { get; set; } = new List<outpatient_clinic>();

    public virtual business_type type { get; set; }

    public virtual ICollection<vet_information> vet_informations { get; set; } = new List<vet_information>();

    public virtual ICollection<ward> wards { get; set; } = new List<ward>();
}