// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class business_type
{
    public int business_type_ID { get; set; }

    public string business_type_name { get; set; }

    public virtual ICollection<business> businesses { get; set; } = new List<business>();

    public virtual ICollection<order_status> order_statusFK_businessTypes { get; set; } = new List<order_status>();

    public virtual ICollection<order_status> order_statusbusiness_types { get; set; } = new List<order_status>();
}