// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class CheckinDetail
{
    public int checkinID { get; set; }

    public int? bookingID { get; set; }

    public int? roomID { get; set; }

    public int? pet_ID { get; set; }

    public virtual Booking booking { get; set; }

    public virtual pet pet { get; set; }

    public virtual Room room { get; set; }
}