// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class hosp_record
{
    public int id { get; set; }

    public DateTime admission_date { get; set; }

    public DateTime? discharge_date { get; set; }

    public string memo { get; set; }

    public int? medical_records_id { get; set; }

    public int? ward_id { get; set; }

    public virtual medical_record medical_records { get; set; }

    public virtual ICollection<nursing_record> nursing_records { get; set; } = new List<nursing_record>();

    public virtual ward ward { get; set; }
}