// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class hosp_history
{
    public int id { get; set; }

    public int? medical_record_id { get; set; }

    public DateTime admission_date { get; set; }

    public DateTime? discharge_date { get; set; }

    public int? nursing_record_id { get; set; }

    public int? ward_id { get; set; }

    public string memo { get; set; }

    public virtual medical_record medical_record { get; set; }

    public virtual nursing_record nursing_record { get; set; }

    public virtual ward ward { get; set; }
}