// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class image_file
{
    public int image_id { get; set; }

    public int? record_type_id { get; set; }

    public int record_id { get; set; }

    public string file_path { get; set; }

    public DateTime? uploaded_at { get; set; }

    public virtual record_type record_type { get; set; }
}