// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class keeper_img
{
    public int ID { get; set; }

    public int? img_type_id { get; set; }

    public string URL { get; set; }

    public string name { get; set; }

    public DateTime? created_at { get; set; }

    public virtual ICollection<article_img> article_imgs { get; set; } = new List<article_img>();

    public virtual keeper_img_type img_type { get; set; }
}