// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class medicine_order_record
{
    public int id { get; set; }

    public int? medical_record_id { get; set; }

    public DateTime? order_datetime { get; set; }

    public int? medicine_generic_name_id { get; set; }

    public string dosage { get; set; }

    public string dosage_form { get; set; }

    public string route { get; set; }

    public string frequency { get; set; }

    public string duration { get; set; }

    public string status { get; set; }

    public virtual medical_record medical_record { get; set; }

    public virtual medicine_generic_name medicine_generic_name { get; set; }

    public virtual ICollection<surgery> surgeries { get; set; } = new List<surgery>();
}