// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class medicine_generic_name
{
    public int id { get; set; }

    public string generic_name { get; set; }

    public string brand_name { get; set; }

    public string route { get; set; }

    public string effects { get; set; }

    public string side_effects { get; set; }

    public virtual ICollection<medicine_order_record> medicine_order_records { get; set; } = new List<medicine_order_record>();
}