// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class medicine_order_detail
{
    public int id { get; set; }

    public int? nurseimg_record_id { get; set; }

    public string status { get; set; }

    public virtual nursing_record nurseimg_record { get; set; }
}