// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class medical_imaging
{
    public int id { get; set; }

    public DateTime? examined_time { get; set; }

    public string findings { get; set; }

    public int? medical_imaging_order_id { get; set; }

    public virtual ICollection<image_file> image_files { get; set; } = new List<image_file>();

    public virtual medical_imaging_order medical_imaging_order { get; set; }
}