// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
//Model不能改
namespace Tailstale.Models;

public partial class medical_record
{
    public int id { get; set; }

    public int? pet_id { get; set; }

    public DateTime? created_at { get; set; }

    public int? outpatient_clinic_id { get; set; }

    public decimal? weight { get; set; }

    public string admission_process { get; set; }

    public string diagnosis { get; set; }

    public string treatment { get; set; }

    public int? biological_test_id { get; set; }

    public string memo { get; set; }

    public int? fee { get; set; }

    public virtual biological_test biological_test { get; set; }

    public virtual ICollection<hosp_history> hosp_histories { get; set; } = new List<hosp_history>();

    public virtual ICollection<medicine_order_record> medicine_order_records { get; set; } = new List<medicine_order_record>();

    public virtual outpatient_clinic outpatient_clinic { get; set; }

    public virtual pet pet { get; set; }

    public virtual ICollection<surgery> surgeries { get; set; } = new List<surgery>();
}