// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class medicine
{
    public int id { get; set; }

    public string medicine_name { get; set; }

    public string effects { get; set; }

    public string side_effects { get; set; }

    public string notice { get; set; }

    public virtual ICollection<medicine_order> medicine_orders { get; set; } = new List<medicine_order>();
}