// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class medicine_order
{
    public int id { get; set; }

    public DateTime start_datetime { get; set; }

    public DateTime end_datetime { get; set; }

    public string order_status { get; set; }

    public int medicine_id { get; set; }

    public string route { get; set; }

    public decimal dosage { get; set; }

    public string frequency { get; set; }

    public int? medical_orders_id { get; set; }

    public virtual medical_order medical_orders { get; set; }

    public virtual medicine medicine { get; set; }
}