// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class medical_imaging_order
{
    public int id { get; set; }

    public DateTime? examined_date { get; set; }

    public string type { get; set; }

    public string examined_area { get; set; }

    public int? medical_orders_id { get; set; }

    public virtual medical_order medical_orders { get; set; }
}