// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class medical_record
{
    public int id { get; set; }

    public int? pet_id { get; set; }

    public DateTime? Datetime { get; set; }

    public decimal? weight { get; set; }

    public string complain { get; set; }

    public string diagnosis { get; set; }

    public string treatment { get; set; }

    public string memo { get; set; }

    public int? fee { get; set; }

    public int? outpatient_clinic_id { get; set; }

    public virtual ICollection<hosp_record> hosp_records { get; set; } = new List<hosp_record>();

    public virtual ICollection<medical_order> medical_orders { get; set; } = new List<medical_order>();

    public virtual outpatient_clinic outpatient_clinic { get; set; }

    public virtual pet pet { get; set; }

    public virtual ICollection<vital_sign_record> vital_sign_records { get; set; } = new List<vital_sign_record>();
}