// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class memo
{
    public int ID { get; set; }

    public int? FK_keeper_ID { get; set; }

    public int? business_ID { get; set; }

    public string content { get; set; }

    public virtual keeper FK_keeper { get; set; }

    public virtual business business { get; set; }
}