// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class Message
{
    public int ID { get; set; }

    public int? FK_User_ID { get; set; }

    public int? FK_Target_ID { get; set; }

    public string content { get; set; }

    public DateTime? created_at { get; set; }

    public virtual keeper FK_Target { get; set; }

    public virtual keeper FK_User { get; set; }
}