// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class myChoice
{
    public int? RoomId { get; set; }

    public int? RoomQuantity { get; set; }
}