// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class order_status
{
    public int ID { get; set; }

    public string status_name { get; set; }

    public int? business_type_ID { get; set; }

    public int? FK_businessType_ID { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual business_type FK_businessType { get; set; }

    public virtual ICollection<Reserve> Reserve { get; set; } = new List<Reserve>();

    public virtual business_type business_type { get; set; }
}