// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class PaymentIndex
{
    public int paymentID { get; set; }

    public int? business_ID { get; set; }

    public int? keeper_ID { get; set; }

    public int? bookingID { get; set; }

    public string cardholderName { get; set; }

    public int? cardNumber { get; set; }

    public DateOnly? expirationDate { get; set; }

    public int? cvvNumber { get; set; }

    public int? paymentAmount { get; set; }

    public byte[] paymentStatus { get; set; }

    public DateTime? paymentTimestamp { get; set; }

    public virtual Booking booking { get; set; }

    public virtual business business { get; set; }

    public virtual keeper keeper { get; set; }
}