// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class person_tag
{
    public int ID { get; set; }

    public int? FK_Keeper_ID { get; set; }

    public string name { get; set; }

    public int? FK_Business_ID { get; set; }

    public virtual business FK_Business { get; set; }

    public virtual keeper FK_Keeper { get; set; }

    public virtual ICollection<using_person_tag> using_person_tags { get; set; } = new List<using_person_tag>();
}