// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class Reserve
{
    public int id { get; set; }

    public int keeper_id { get; set; }

    public string pet_name { get; set; }

    public int business_ID { get; set; }

    public DateTime time { get; set; }

    public string service_name { get; set; }

    public DateTime? created_at { get; set; }

    public virtual business business { get; set; }

    public virtual keeper keeper { get; set; }
}