// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class Review
{
    public int reviewID { get; set; }

    public int? roomID { get; set; }

    public int? keeper_ID { get; set; }

    public int? reviewRating { get; set; }

    public string reviewText { get; set; }

    public DateTime? reviewDate { get; set; }

    public virtual keeper keeper { get; set; }

    public virtual Room room { get; set; }
}