// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class Room
{
    public int roomID { get; set; }

    public int hotelID { get; set; }

    public string roomSpecies { get; set; }

    public int? roomPrice { get; set; }

    public int? roomDiscount { get; set; }

    public int? roomReserve { get; set; }

    public string roomDescrep { get; set; }

    public int? FK_roomImg_ID { get; set; }

    public int? FK_roomType_ID { get; set; }

    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    public virtual ICollection<CheckinDetail> CheckinDetails { get; set; } = new List<CheckinDetail>();

    public virtual business_img_type FK_roomImg { get; set; }

    public virtual roomType FK_roomType { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual business hotel { get; set; }
}