// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class Service
{
    public int id { get; set; }

    public int business_ID { get; set; }

    public string category { get; set; }

    public string service_name { get; set; }

    public string service_content { get; set; }

    public string service_img { get; set; }

    public string price { get; set; }

    public virtual ICollection<Store_Service> Store_Services { get; set; } = new List<Store_Service>();

    public virtual business business { get; set; }
}