// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class status
{
    public int ID { get; set; }

    public string status_name { get; set; }

    public virtual ICollection<business> businesses { get; set; } = new List<business>();

    public virtual ICollection<keeper> keepers { get; set; } = new List<keeper>();
}