// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Tailstale.Models;

public partial class Store_Service
{
    public int id { get; set; }

    public int business_ID { get; set; }

    
    [Required(ErrorMessage = "sservice_id欄位未填寫")]
    public int service_id { get; set; }

    public virtual business business { get; set; }

    public virtual Service service { get; set; }
}