// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Tailstale.Models;

public partial class TailstaleContext : DbContext
{
    public TailstaleContext(DbContextOptions<TailstaleContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Appointment> Appointments { get; set; }

    public virtual DbSet<Beautician> Beauticians { get; set; }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<BookingDetail> BookingDetails { get; set; }

    public virtual DbSet<Business_hour> Business_hours { get; set; }

    public virtual DbSet<CheckinDetail> CheckinDetails { get; set; }

    public virtual DbSet<Consumption_Record> Consumption_Records { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<PaymentInfo> PaymentInfos { get; set; }

    public virtual DbSet<Reserve> Reserves { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<Room> Rooms { get; set; }

    public virtual DbSet<Service> Services { get; set; }

    public virtual DbSet<article> articles { get; set; }

    public virtual DbSet<article_img> article_imgs { get; set; }

    public virtual DbSet<biological_test> biological_tests { get; set; }

    public virtual DbSet<biological_test_order> biological_test_orders { get; set; }

    public virtual DbSet<business> businesses { get; set; }

    public virtual DbSet<business_img> business_imgs { get; set; }

    public virtual DbSet<business_img_type> business_img_types { get; set; }

    public virtual DbSet<business_type> business_types { get; set; }

    public virtual DbSet<daily_outpatient_clinic_schedule> daily_outpatient_clinic_schedules { get; set; }

    public virtual DbSet<department> departments { get; set; }

    public virtual DbSet<hosp_record> hosp_records { get; set; }

    public virtual DbSet<image_file> image_files { get; set; }

    public virtual DbSet<keeper> keepers { get; set; }

    public virtual DbSet<keeper_img> keeper_imgs { get; set; }

    public virtual DbSet<keeper_img_type> keeper_img_types { get; set; }

    public virtual DbSet<medical_imaging> medical_imagings { get; set; }

    public virtual DbSet<medical_imaging_order> medical_imaging_orders { get; set; }

    public virtual DbSet<medical_order> medical_orders { get; set; }

    public virtual DbSet<medical_record> medical_records { get; set; }

    public virtual DbSet<medicine> medicines { get; set; }

    public virtual DbSet<medicine_order> medicine_orders { get; set; }

    public virtual DbSet<member_status> member_statuses { get; set; }

    public virtual DbSet<memo> memos { get; set; }

    public virtual DbSet<order_status> order_statuses { get; set; }

    public virtual DbSet<outpatient_clinic> outpatient_clinics { get; set; }

    public virtual DbSet<outpatient_clinic_timeslot> outpatient_clinic_timeslots { get; set; }

    public virtual DbSet<person_tag> person_tags { get; set; }

    public virtual DbSet<pet> pets { get; set; }

    public virtual DbSet<pet_type> pet_types { get; set; }

    public virtual DbSet<roomType> roomTypes { get; set; }

    public virtual DbSet<speciman> specimen { get; set; }

    public virtual DbSet<surgery> surgeries { get; set; }

    public virtual DbSet<tag> tags { get; set; }

    public virtual DbSet<treatment> treatments { get; set; }

    public virtual DbSet<using_person_tag> using_person_tags { get; set; }

    public virtual DbSet<using_tag> using_tags { get; set; }

    public virtual DbSet<vet_information> vet_informations { get; set; }

    public virtual DbSet<vital_sign_record> vital_sign_records { get; set; }

    public virtual DbSet<ward> wards { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Appointment>(entity =>
        {
            entity.HasKey(e => e.Appointment_ID).HasName("PK__Appointm__FD01B50322C48BC0");

            entity.ToTable("Appointment");

            entity.Property(e => e.registration_time)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Appointment_statusNavigation).WithMany(p => p.Appointments)
                .HasForeignKey(d => d.Appointment_status)
                .HasConstraintName("FK__Appointme__Appoi__02FC7413");

            entity.HasOne(d => d.daily_outpatient_clinic_schedule).WithMany(p => p.Appointments)
                .HasForeignKey(d => d.daily_outpatient_clinic_schedule_ID)
                .HasConstraintName("FK__Appointme__daily__02084FDA");

            entity.HasOne(d => d.keeper).WithMany(p => p.Appointments)
                .HasForeignKey(d => d.keeper_ID)
                .HasConstraintName("FK__Appointme__keepe__00200768");

            entity.HasOne(d => d.pet).WithMany(p => p.Appointments)
                .HasForeignKey(d => d.pet_ID)
                .HasConstraintName("FK__Appointme__pet_I__7F2BE32F");
        });

        modelBuilder.Entity<Beautician>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Beautici__3213E83F67424BA6");

            entity.ToTable("Beautician");

            entity.Property(e => e.Highest_license).HasMaxLength(255);
            entity.Property(e => e.Remark).HasMaxLength(300);
            entity.Property(e => e.gender)
                .IsRequired()
                .HasMaxLength(3);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.phone)
                .IsRequired()
                .HasMaxLength(16);
            entity.Property(e => e.photo).HasMaxLength(255);

            entity.HasOne(d => d.business).WithMany(p => p.Beauticians)
                .HasForeignKey(d => d.business_ID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Beauticia__busin__6EC0713C");
        });

        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.bookingID).HasName("PK__Booking__C6D03BEDCEE71DB7");

            entity.ToTable("Booking");

            entity.Property(e => e.bookingDate).HasColumnType("datetime");
            entity.Property(e => e.checkinDate).HasColumnType("datetime");
            entity.Property(e => e.checkoutDate).HasColumnType("datetime");

            entity.HasOne(d => d.bookingStatusNavigation).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.bookingStatus)
                .HasConstraintName("FK__Booking__booking__4E53A1AA");

            entity.HasOne(d => d.hotel).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.hotelID)
                .HasConstraintName("FK__Booking__hotelID__4C6B5938");

            entity.HasOne(d => d.keeper).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.keeper_ID)
                .HasConstraintName("FK__Booking__keeper___4D5F7D71");
        });

        modelBuilder.Entity<BookingDetail>(entity =>
        {
            entity.HasKey(e => e.bdID).HasName("PK__BookingD__4E75390FBE1D20AF");

            entity.HasOne(d => d.booking).WithMany(p => p.BookingDetails)
                .HasForeignKey(d => d.bookingID)
                .HasConstraintName("FK__BookingDe__booki__503BEA1C");

            entity.HasOne(d => d.room).WithMany(p => p.BookingDetails)
                .HasForeignKey(d => d.roomID)
                .HasConstraintName("FK__BookingDe__roomI__4F47C5E3");
        });

        modelBuilder.Entity<Business_hour>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Business__3213E83F9C5AEFBA");

            entity.ToTable("Business_hour");

            entity.Property(e => e.close_time).HasDefaultValue(new TimeOnly(19, 0, 0));
            entity.Property(e => e.open_time).HasDefaultValue(new TimeOnly(10, 0, 0));
            entity.Property(e => e.people_limit).HasDefaultValue(2);

            entity.HasOne(d => d.business).WithMany(p => p.Business_hours)
                .HasForeignKey(d => d.business_ID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Business___busin__634EBE90");
        });

        modelBuilder.Entity<CheckinDetail>(entity =>
        {
            entity.HasKey(e => e.checkinID).HasName("PK__CheckinD__CF1A6A4177428216");

            entity.HasOne(d => d.booking).WithMany(p => p.CheckinDetails)
                .HasForeignKey(d => d.bookingID)
                .HasConstraintName("FK__CheckinDe__booki__55009F39");

            entity.HasOne(d => d.pet).WithMany(p => p.CheckinDetails)
                .HasForeignKey(d => d.pet_ID)
                .HasConstraintName("FK__CheckinDe__pet_I__56E8E7AB");

            entity.HasOne(d => d.room).WithMany(p => p.CheckinDetails)
                .HasForeignKey(d => d.roomID)
                .HasConstraintName("FK__CheckinDe__roomI__55F4C372");
        });

        modelBuilder.Entity<Consumption_Record>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Consumpt__3213E83F15D8AB19");

            entity.ToTable("Consumption_Record");

            entity.Property(e => e.after_photo).HasMaxLength(255);
            entity.Property(e => e.before_photo).HasMaxLength(255);
            entity.Property(e => e.end_time)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.pet_name)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.pet_weight).HasColumnType("decimal(4, 1)");
            entity.Property(e => e.service_name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.time).HasColumnType("datetime");

            entity.HasOne(d => d.beautician).WithMany(p => p.Consumption_Records)
                .HasForeignKey(d => d.beautician_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Consumpti__beaut__74794A92");

            entity.HasOne(d => d.business).WithMany(p => p.Consumption_Records)
                .HasForeignKey(d => d.business_ID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Consumpti__busin__719CDDE7");

            entity.HasOne(d => d.keeper).WithMany(p => p.Consumption_Records)
                .HasForeignKey(d => d.keeper_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Consumpti__keepe__73852659");
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Message__3214EC27B632FC8B");

            entity.ToTable("Message");

            entity.Property(e => e.content).HasMaxLength(256);
            entity.Property(e => e.created_at)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.FK_Target).WithMany(p => p.MessageFK_Targets)
                .HasForeignKey(d => d.FK_Target_ID)
                .HasConstraintName("FK__Message__FK_Targ__0B5CAFEA");

            entity.HasOne(d => d.FK_User).WithMany(p => p.MessageFK_Users)
                .HasForeignKey(d => d.FK_User_ID)
                .HasConstraintName("FK__Message__FK_User__0A688BB1");
        });

        modelBuilder.Entity<PaymentInfo>(entity =>
        {
            entity.HasKey(e => e.paymentID).HasName("PK__PaymentI__A0D9EFA60D0B09F6");

            entity.ToTable("PaymentInfo");

            entity.Property(e => e.cardholderName).HasMaxLength(20);
            entity.Property(e => e.paymentStatus)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.paymentTimestamp).HasColumnType("datetime");

            entity.HasOne(d => d.booking).WithMany(p => p.PaymentInfos)
                .HasForeignKey(d => d.bookingID)
                .HasConstraintName("FK__PaymentIn__booki__540C7B00");

            entity.HasOne(d => d.business).WithMany(p => p.PaymentInfos)
                .HasForeignKey(d => d.business_ID)
                .HasConstraintName("FK__PaymentIn__busin__4A8310C6");

            entity.HasOne(d => d.keeper).WithMany(p => p.PaymentInfos)
                .HasForeignKey(d => d.keeper_ID)
                .HasConstraintName("FK__PaymentIn__keepe__531856C7");
        });

        modelBuilder.Entity<Reserve>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Reserve__3213E83F7077A9D6");

            entity.ToTable("Reserve");

            entity.Property(e => e.created_at)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.pet_name)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.service_name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.time).HasColumnType("datetime");

            entity.HasOne(d => d.business).WithMany(p => p.Reserves)
                .HasForeignKey(d => d.business_ID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reserve__busines__690797E6");

            entity.HasOne(d => d.keeper).WithMany(p => p.Reserves)
                .HasForeignKey(d => d.keeper_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reserve__keeper___6BE40491");

            entity.HasOne(d => d.statusNavigation).WithMany(p => p.Reserves)
                .HasForeignKey(d => d.status)
                .HasConstraintName("FK__Reserve__status__6AEFE058");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.reviewID).HasName("PK__Review__2ECD6E24E95EE377");

            entity.ToTable("Review");

            entity.Property(e => e.reviewDate).HasColumnType("datetime");
            entity.Property(e => e.reviewText).HasMaxLength(255);

            entity.HasOne(d => d.keeper).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.keeper_ID)
                .HasConstraintName("FK__Review__keeper_I__5224328E");

            entity.HasOne(d => d.room).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.roomID)
                .HasConstraintName("FK__Review__roomID__51300E55");
        });

        modelBuilder.Entity<Room>(entity =>
        {
            entity.HasKey(e => e.roomID).HasName("PK__Rooms__6C3BF5DE808984EC");

            entity.Property(e => e.roomDescrep).HasMaxLength(255);
            entity.Property(e => e.roomSpecies).HasMaxLength(10);

            entity.HasOne(d => d.FK_roomImg).WithMany(p => p.Rooms)
                .HasForeignKey(d => d.FK_roomImg_ID)
                .HasConstraintName("FK_roomImg_ID");

            entity.HasOne(d => d.FK_roomType).WithMany(p => p.Rooms)
                .HasForeignKey(d => d.FK_roomType_ID)
                .HasConstraintName("FK__Rooms__FK_roomTy__5BAD9CC8");

            entity.HasOne(d => d.hotel).WithMany(p => p.Rooms)
                .HasForeignKey(d => d.hotelID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Rooms__hotelID__4B7734FF");
        });

        modelBuilder.Entity<Service>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Service__3213E83FA84DE1F1");

            entity.ToTable("Service");

            entity.Property(e => e.category)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.created_at)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.price)
                .IsRequired()
                .HasMaxLength(15);
            entity.Property(e => e.service_content)
                .IsRequired()
                .HasMaxLength(600);
            entity.Property(e => e.service_img).HasMaxLength(255);
            entity.Property(e => e.service_name)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.business).WithMany(p => p.Services)
                .HasForeignKey(d => d.business_ID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Service__busines__5F7E2DAC");
        });

        modelBuilder.Entity<article>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__article__3214EC27D605DA5C");

            entity.ToTable("article");

            entity.Property(e => e.content).HasMaxLength(1024);
            entity.Property(e => e.created_at)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.parent_ID).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.FK_Business).WithMany(p => p.articles)
                .HasForeignKey(d => d.FK_Business_ID)
                .HasConstraintName("FK__article__FK_Busi__1209AD79");

            entity.HasOne(d => d.FK_Keeper).WithMany(p => p.articles)
                .HasForeignKey(d => d.FK_Keeper_ID)
                .HasConstraintName("FK__article__FK_Keep__7755B73D");

            entity.HasOne(d => d.parent).WithMany(p => p.Inverseparent)
                .HasForeignKey(d => d.parent_ID)
                .HasConstraintName("FK__article__parent___793DFFAF");
        });

        modelBuilder.Entity<article_img>(entity =>
        {
            entity.HasKey(e => e.AI_ID).HasName("PK__article___AB500D4D54EDE6E5");

            entity.ToTable("article_img");

            entity.HasOne(d => d.FK_Business_img).WithMany(p => p.article_imgs)
                .HasForeignKey(d => d.FK_Business_img_ID)
                .HasConstraintName("FK__article_i__FK_Bu__11158940");

            entity.HasOne(d => d.FK_Keeper_img).WithMany(p => p.article_imgs)
                .HasForeignKey(d => d.FK_Keeper_img_ID)
                .HasConstraintName("FK__article_i__FK_Ke__10216507");

            entity.HasOne(d => d.FK_article).WithMany(p => p.article_imgs)
                .HasForeignKey(d => d.FK_article_ID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__article_i__FK_ar__0F2D40CE");
        });

        modelBuilder.Entity<biological_test>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__biologic__3213E83F48C47CCD");

            entity.ToTable("biological_test");

            entity.Property(e => e.findings).HasMaxLength(300);
            entity.Property(e => e.lab_data).HasColumnType("decimal(7, 2)");
            entity.Property(e => e.test_time)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.biological_test_order).WithMany(p => p.biological_tests)
                .HasForeignKey(d => d.biological_test_order_id)
                .HasConstraintName("FK__biologica__biolo__2739D489");

            entity.HasOne(d => d.specimen).WithMany(p => p.biological_tests)
                .HasForeignKey(d => d.specimen_id)
                .HasConstraintName("FK__biologica__speci__2645B050");
        });

        modelBuilder.Entity<biological_test_order>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__biologic__3213E83FE7595F73");

            entity.ToTable("biological_test_order");

            entity.Property(e => e.order_time)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.test_time)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.medical_orders).WithMany(p => p.biological_test_orders)
                .HasForeignKey(d => d.medical_orders_id)
                .HasConstraintName("FK__biologica__medic__22751F6C");

            entity.HasOne(d => d.specimen).WithMany(p => p.biological_test_orders)
                .HasForeignKey(d => d.specimen_id)
                .HasConstraintName("FK__biologica__speci__2180FB33");
        });

        modelBuilder.Entity<business>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__business__3214EC27226A53D9");

            entity.ToTable("business");

            entity.Property(e => e.address)
                .HasMaxLength(200)
                .HasDefaultValue("未填寫");
            entity.Property(e => e.created_at)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.email)
                .HasMaxLength(100)
                .HasDefaultValue("未填寫");
            entity.Property(e => e.geoJson).HasDefaultValue("未填寫");
            entity.Property(e => e.license_number)
                .HasMaxLength(50)
                .HasDefaultValue("未填寫");
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.phone)
                .HasMaxLength(30)
                .HasDefaultValue("未填寫");
            entity.Property(e => e.salt)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.business_statusNavigation).WithMany(p => p.businesses)
                .HasForeignKey(d => d.business_status)
                .HasConstraintName("FK__business__busine__5AEE82B9");

            entity.HasOne(d => d.type).WithMany(p => p.businesses)
                .HasForeignKey(d => d.type_ID)
                .HasConstraintName("FK__business__type_I__5535A963");
        });

        modelBuilder.Entity<business_img>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__business__3214EC27B7E0BBCA");

            entity.ToTable("business_img");

            entity.Property(e => e.URL).HasMaxLength(512);
            entity.Property(e => e.created_at)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.name)
                .HasMaxLength(256)
                .HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.img_type).WithMany(p => p.business_imgs)
                .HasForeignKey(d => d.img_type_id)
                .HasConstraintName("FK__business___img_t__628FA481");
        });

        modelBuilder.Entity<business_img_type>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__business__3214EC2715258BCF");

            entity.ToTable("business_img_type");

            entity.Property(e => e.created_at)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.typename).HasMaxLength(512);

            entity.HasOne(d => d.FK_business).WithMany(p => p.business_img_types)
                .HasForeignKey(d => d.FK_business_id)
                .HasConstraintName("FK__business___FK_bu__5EBF139D");
        });

        modelBuilder.Entity<business_type>(entity =>
        {
            entity.HasKey(e => e.business_type_ID).HasName("PK__business__2F9BFA517F5AD248");

            entity.ToTable("business_type");

            entity.Property(e => e.business_type_name)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<daily_outpatient_clinic_schedule>(entity =>
        {
            entity.HasKey(e => e.daily_outpatient_clinic_schedule_ID).HasName("PK__daily_ou__A98BAD4E78CB8E6F");

            entity.ToTable("daily_outpatient_clinic_schedule");

            entity.Property(e => e.created_date).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.outpatient_clinic).WithMany(p => p.daily_outpatient_clinic_schedules)
                .HasForeignKey(d => d.outpatient_clinic_ID)
                .HasConstraintName("FK__daily_out__outpa__787EE5A0");
        });

        modelBuilder.Entity<department>(entity =>
        {
            entity.HasKey(e => e.department_ID).HasName("PK__departme__C22220EA224CDBC6");

            entity.ToTable("department");

            entity.Property(e => e.department_name)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.business).WithMany(p => p.departments)
                .HasForeignKey(d => d.business_ID)
                .HasConstraintName("FK__departmen__busin__6B24EA82");
        });

        modelBuilder.Entity<hosp_record>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__hosp_rec__3213E83F1D2CDEAC");

            entity.Property(e => e.admission_date).HasColumnType("datetime");
            entity.Property(e => e.discharge_date).HasColumnType("datetime");
            entity.Property(e => e.memo).HasMaxLength(200);

            entity.HasOne(d => d.medical_records).WithMany(p => p.hosp_records)
                .HasForeignKey(d => d.medical_records_id)
                .HasConstraintName("FK__hosp_reco__medic__3D2915A8");

            entity.HasOne(d => d.ward).WithMany(p => p.hosp_records)
                .HasForeignKey(d => d.ward_id)
                .HasConstraintName("FK__hosp_reco__ward___3E1D39E1");
        });

        modelBuilder.Entity<image_file>(entity =>
        {
            entity.HasKey(e => e.image_id).HasName("PK__image_fi__DC9AC955567BDFC2");

            entity.Property(e => e.file_name)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.medical_imaging).WithMany(p => p.image_files)
                .HasForeignKey(d => d.medical_imaging_id)
                .HasConstraintName("FK__image_fil__medic__3A4CA8FD");
        });

        modelBuilder.Entity<keeper>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__keeper__3214EC279E64EA99");

            entity.ToTable("keeper");

            entity.Property(e => e.address).HasMaxLength(200);
            entity.Property(e => e.created_at)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.phone).HasMaxLength(15);
            entity.Property(e => e.salt)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.statusNavigation).WithMany(p => p.keepers)
                .HasForeignKey(d => d.status)
                .HasConstraintName("FK__keeper__status__3A81B327");
        });

        modelBuilder.Entity<keeper_img>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__keeper_i__3214EC2710E5BF01");

            entity.ToTable("keeper_img");

            entity.Property(e => e.URL).HasMaxLength(512);
            entity.Property(e => e.created_at)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.name)
                .HasMaxLength(256)
                .HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.img_type).WithMany(p => p.keeper_imgs)
                .HasForeignKey(d => d.img_type_id)
                .HasConstraintName("FK__keeper_im__img_t__4222D4EF");
        });

        modelBuilder.Entity<keeper_img_type>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__keeper_i__3214EC270E68AED2");

            entity.ToTable("keeper_img_type");

            entity.Property(e => e.created_at)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.typename).HasMaxLength(512);

            entity.HasOne(d => d.FK_Keeper).WithMany(p => p.keeper_img_types)
                .HasForeignKey(d => d.FK_Keeper_id)
                .HasConstraintName("FK__keeper_im__FK_Ke__3E52440B");
        });

        modelBuilder.Entity<medical_imaging>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__medical___3213E83FEC1725FB");

            entity.ToTable("medical_imaging");

            entity.Property(e => e.examined_time)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.findings).HasMaxLength(300);

            entity.HasOne(d => d.medical_imaging_order).WithMany(p => p.medical_imagings)
                .HasForeignKey(d => d.medical_imaging_order_id)
                .HasConstraintName("FK__medical_i__medic__37703C52");
        });

        modelBuilder.Entity<medical_imaging_order>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__medical___3213E83F0D670209");

            entity.ToTable("medical_imaging_order");

            entity.Property(e => e.examined_area).HasMaxLength(50);
            entity.Property(e => e.examined_date)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.type).HasMaxLength(50);

            entity.HasOne(d => d.medical_orders).WithMany(p => p.medical_imaging_orders)
                .HasForeignKey(d => d.medical_orders_id)
                .HasConstraintName("FK__medical_i__medic__339FAB6E");
        });

        modelBuilder.Entity<medical_order>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__medical___3213E83F6DD2FE3A");

            entity.Property(e => e.datetime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.medical_records).WithMany(p => p.medical_orders)
                .HasForeignKey(d => d.medical_records_id)
                .HasConstraintName("FK__medical_o__medic__114A936A");

            entity.HasOne(d => d.pet).WithMany(p => p.medical_orders)
                .HasForeignKey(d => d.pet_id)
                .HasConstraintName("FK__medical_o__pet_i__10566F31");
        });

        modelBuilder.Entity<medical_record>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__medical___3213E83F45DD45BA");

            entity.Property(e => e.Datetime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.complain)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.diagnosis)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.memo).HasMaxLength(200);
            entity.Property(e => e.weight).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.outpatient_clinic).WithMany(p => p.medical_records)
                .HasForeignKey(d => d.outpatient_clinic_id)
                .HasConstraintName("FK__medical_r__outpa__07C12930");

            entity.HasOne(d => d.pet).WithMany(p => p.medical_records)
                .HasForeignKey(d => d.pet_id)
                .HasConstraintName("FK__medical_r__pet_i__05D8E0BE");
        });

        modelBuilder.Entity<medicine>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__medicine__3213E83FDADF77AB");

            entity.ToTable("medicine");

            entity.Property(e => e.effects).HasMaxLength(200);
            entity.Property(e => e.medicine_name).HasMaxLength(50);
            entity.Property(e => e.notice).HasMaxLength(50);
            entity.Property(e => e.side_effects).HasMaxLength(200);
        });

        modelBuilder.Entity<medicine_order>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__medicine__3213E83F7288DDD0");

            entity.Property(e => e.dosage).HasColumnType("decimal(3, 1)");
            entity.Property(e => e.end_datetime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.frequency)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.order_status)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValue("opd");
            entity.Property(e => e.route)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.start_datetime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.medical_orders).WithMany(p => p.medicine_orders)
                .HasForeignKey(d => d.medical_orders_id)
                .HasConstraintName("FK__medicine___medic__19DFD96B");

            entity.HasOne(d => d.medicine).WithMany(p => p.medicine_orders)
                .HasForeignKey(d => d.medicine_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__medicine___medic__18EBB532");
        });

        modelBuilder.Entity<member_status>(entity =>
        {
            entity.HasKey(e => e.member_status_ID).HasName("PK__member_s__819644FEF5E7B1B8");

            entity.ToTable("member_status");

            entity.Property(e => e.status_name)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<memo>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__memo__3214EC2746FDACF0");

            entity.ToTable("memo");

            entity.Property(e => e.content).HasMaxLength(1000);

            entity.HasOne(d => d.FK_keeper).WithMany(p => p.memos)
                .HasForeignKey(d => d.FK_keeper_ID)
                .HasConstraintName("FK__memo__FK_keeper___6754599E");

            entity.HasOne(d => d.business).WithMany(p => p.memos)
                .HasForeignKey(d => d.business_ID)
                .HasConstraintName("FK__memo__business_I__68487DD7");
        });

        modelBuilder.Entity<order_status>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__order_st__3214EC2763EA79EF");

            entity.ToTable("order_status");

            entity.Property(e => e.status_name)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.FK_businessType).WithMany(p => p.order_statusFK_businessTypes)
                .HasForeignKey(d => d.FK_businessType_ID)
                .HasConstraintName("FK_businessType_ID");

            entity.HasOne(d => d.business_type).WithMany(p => p.order_statusbusiness_types)
                .HasForeignKey(d => d.business_type_ID)
                .HasConstraintName("FK__order_sta__busin__52593CB8");
        });

        modelBuilder.Entity<outpatient_clinic>(entity =>
        {
            entity.HasKey(e => e.outpatient_clinic_ID).HasName("PK__outpatie__6AA2EF9497E5C9DD");

            entity.ToTable("outpatient_clinic");

            entity.Property(e => e.dayofweek).HasMaxLength(20);
            entity.Property(e => e.outpatient_clinic_name)
                .IsRequired()
                .HasMaxLength(30);

            entity.HasOne(d => d.outpatient_clinic_timeslot).WithMany(p => p.outpatient_clinics)
                .HasForeignKey(d => d.outpatient_clinic_timeslot_ID)
                .HasConstraintName("FK__outpatien__outpa__74AE54BC");

            entity.HasOne(d => d.vet).WithMany(p => p.outpatient_clinics)
                .HasForeignKey(d => d.vet_ID)
                .HasConstraintName("FK__outpatien__vet_I__75A278F5");
        });

        modelBuilder.Entity<outpatient_clinic_timeslot>(entity =>
        {
            entity.HasKey(e => e.outpatient_clinic_timeslot_ID).HasName("PK__outpatie__C88688B9CB8343DF");

            entity.ToTable("outpatient_clinic_timeslot");

            entity.Property(e => e.outpatient_clinic_timeslot_name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<person_tag>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__person_t__3214EC27EA0EF155");

            entity.Property(e => e.name).HasMaxLength(128);

            entity.HasOne(d => d.FK_Business).WithMany(p => p.person_tags)
                .HasForeignKey(d => d.FK_Business_ID)
                .HasConstraintName("FK__person_ta__FK_Bu__19AACF41");

            entity.HasOne(d => d.FK_Keeper).WithMany(p => p.person_tags)
                .HasForeignKey(d => d.FK_Keeper_ID)
                .HasConstraintName("FK__person_ta__FK_Ke__02C769E9");
        });

        modelBuilder.Entity<pet>(entity =>
        {
            entity.HasKey(e => e.pet_ID).HasName("PK__pet__3913D166B739927A");

            entity.ToTable("pet");

            entity.Property(e => e.allergy)
                .HasMaxLength(200)
                .HasDefaultValue("無過敏記錄");
            entity.Property(e => e.chip_ID)
                .HasMaxLength(50)
                .HasDefaultValue("無晶片");
            entity.Property(e => e.chronic_dis)
                .HasMaxLength(200)
                .HasDefaultValue("無慢性病史");
            entity.Property(e => e.created_at)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.memo)
                .HasMaxLength(200)
                .HasDefaultValue("無備註");
            entity.Property(e => e.name).HasMaxLength(100);
            entity.Property(e => e.pet_weight).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.vaccine)
                .HasMaxLength(100)
                .HasDefaultValue("無疫苗施打紀錄");

            entity.HasOne(d => d.keeper).WithMany(p => p.pets)
                .HasForeignKey(d => d.keeper_ID)
                .HasConstraintName("FK__pet__keeper_ID__47DBAE45");

            entity.HasOne(d => d.pet_type).WithMany(p => p.pets)
                .HasForeignKey(d => d.pet_type_ID)
                .HasConstraintName("FK__pet__pet_type_ID__46E78A0C");
        });

        modelBuilder.Entity<pet_type>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__pet_type__3214EC27CB8D16E9");

            entity.ToTable("pet_type");

            entity.Property(e => e.breed)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.species)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<roomType>(entity =>
        {
            entity.HasKey(e => e.roomType_ID).HasName("PK__roomType__28045B88EA42A548");

            entity.ToTable("roomType");

            entity.Property(e => e.roomType1)
                .HasMaxLength(30)
                .HasColumnName("roomType");

            entity.HasOne(d => d.FK_business).WithMany(p => p.roomTypes)
                .HasForeignKey(d => d.FK_businessID)
                .HasConstraintName("FK__roomType__FK_bus__5AB9788F");
        });

        modelBuilder.Entity<speciman>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__specimen__3213E83F122B687D");

            entity.Property(e => e.normal_range_max).HasColumnType("decimal(7, 3)");
            entity.Property(e => e.normal_range_min).HasColumnType("decimal(7, 3)");
            entity.Property(e => e.specimen_name).HasMaxLength(50);
            entity.Property(e => e.test_name).HasMaxLength(50);

            entity.HasOne(d => d.pet_typeNavigation).WithMany(p => p.specimen)
                .HasForeignKey(d => d.pet_type)
                .HasConstraintName("FK__specimen__pet_ty__1CBC4616");
        });

        modelBuilder.Entity<surgery>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__surgery__3213E83FDB4C8E64");

            entity.ToTable("surgery");

            entity.Property(e => e.anesthesia).HasMaxLength(30);
            entity.Property(e => e.findings).HasMaxLength(300);
            entity.Property(e => e.op_duration).HasMaxLength(10);
            entity.Property(e => e.start_time).HasColumnType("datetime");
            entity.Property(e => e.technique).HasMaxLength(100);

            entity.HasOne(d => d.medical_orders).WithMany(p => p.surgeries)
                .HasForeignKey(d => d.medical_orders_id)
                .HasConstraintName("FK__surgery__medical__2FCF1A8A");
        });

        modelBuilder.Entity<tag>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__tags__3214EC273FFE86DF");

            entity.Property(e => e.name).HasMaxLength(128);
        });

        modelBuilder.Entity<treatment>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__treatmen__3213E83F7DF6BF20");

            entity.ToTable("treatment");

            entity.Property(e => e.frequency)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValue("once");
            entity.Property(e => e.item)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.order_status)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValue("opd");
            entity.Property(e => e.start_datetime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.medical_orders).WithMany(p => p.treatments)
                .HasForeignKey(d => d.medical_orders_id)
                .HasConstraintName("FK__treatment__medic__2CF2ADDF");
        });

        modelBuilder.Entity<using_person_tag>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__using_pe__3214EC27AC4BFD9B");

            entity.HasOne(d => d.FK_Business).WithMany(p => p.using_person_tags)
                .HasForeignKey(d => d.FK_Business_ID)
                .HasConstraintName("FK__using_per__FK_Bu__12FDD1B2");

            entity.HasOne(d => d.FK_Keeper).WithMany(p => p.using_person_tags)
                .HasForeignKey(d => d.FK_Keeper_ID)
                .HasConstraintName("FK__using_per__FK_Ke__05A3D694");

            entity.HasOne(d => d.FK_article).WithMany(p => p.using_person_tags)
                .HasForeignKey(d => d.FK_article_ID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__using_per__FK_ar__0697FACD");

            entity.HasOne(d => d.FK_person_tags).WithMany(p => p.using_person_tags)
                .HasForeignKey(d => d.FK_person_tags_ID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__using_per__FK_pe__078C1F06");
        });

        modelBuilder.Entity<using_tag>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__using_ta__3214EC270BC0AE16");

            entity.HasOne(d => d.FK_article).WithMany(p => p.using_tags)
                .HasForeignKey(d => d.FK_article_ID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__using_tag__FK_ar__7EF6D905");

            entity.HasOne(d => d.FK_tags).WithMany(p => p.using_tags)
                .HasForeignKey(d => d.FK_tags_ID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__using_tag__FK_ta__7FEAFD3E");
        });

        modelBuilder.Entity<vet_information>(entity =>
        {
            entity.HasKey(e => e.vet_ID).HasName("PK__vet_info__D816DB2B507B4F0D");

            entity.Property(e => e.license_number).HasMaxLength(50);
            entity.Property(e => e.profile).HasMaxLength(500);
            entity.Property(e => e.vet_name).HasMaxLength(100);

            entity.HasOne(d => d.business).WithMany(p => p.vet_informations)
                .HasForeignKey(d => d.business_ID)
                .HasConstraintName("FK__vet_infor__busin__6E01572D");

            entity.HasOne(d => d.business_img).WithMany(p => p.vet_informations)
                .HasForeignKey(d => d.business_img_ID)
                .HasConstraintName("FK__vet_infor__busin__6FE99F9F");

            entity.HasOne(d => d.department).WithMany(p => p.vet_informations)
                .HasForeignKey(d => d.department_ID)
                .HasConstraintName("FK__vet_infor__depar__6EF57B66");
        });

        modelBuilder.Entity<vital_sign_record>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__vital_si__3213E83F7F9D3AD1");

            entity.ToTable("vital_sign_record");

            entity.Property(e => e.BT).HasColumnType("decimal(3, 1)");
            entity.Property(e => e.memo)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValue("nil");
            entity.Property(e => e.taketime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.medical_records).WithMany(p => p.vital_sign_records)
                .HasForeignKey(d => d.medical_records_id)
                .HasConstraintName("FK__vital_sig__medic__0C85DE4D");
        });

        modelBuilder.Entity<ward>(entity =>
        {
            entity.HasKey(e => e.ward_ID).HasName("PK__ward__396CB5D5B66F5183");

            entity.ToTable("ward");

            entity.Property(e => e.memo).HasMaxLength(100);
            entity.Property(e => e.ward_name).HasMaxLength(100);

            entity.HasOne(d => d.business).WithMany(p => p.wards)
                .HasForeignKey(d => d.business_ID)
                .HasConstraintName("FK__ward__business_I__7C4F7684");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}