// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class treatment
{
    public int id { get; set; }

    public DateTime start_datetime { get; set; }

    public string order_status { get; set; }

    public string item { get; set; }

    public string frequency { get; set; }

    public int? medical_orders_id { get; set; }

    public virtual medical_order medical_orders { get; set; }
}