// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class user_photo
{
    public int ID { get; set; }

    public int? FK_Keeper_ID { get; set; }

    public string name { get; set; }

    public virtual keeper FK_Keeper { get; set; }
}