// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class using_person_tag
{
    public int ID { get; set; }

    public int? FK_Keeper_ID { get; set; }

    public int FK_article_ID { get; set; }

    public int FK_person_tags_ID { get; set; }

    public int? FK_Business_ID { get; set; }

    public virtual business FK_Business { get; set; }

    public virtual keeper FK_Keeper { get; set; }

    public virtual article FK_article { get; set; }

    public virtual person_tag FK_person_tags { get; set; }
}