// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class using_tag
{
    public int ID { get; set; }

    public int FK_article_ID { get; set; }

    public int FK_tags_ID { get; set; }

    public DateTime? created_at { get; set; }

    public virtual article FK_article { get; set; }

    public virtual tag FK_tags { get; set; }
}