// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class vet_information
{
    public int vet_ID { get; set; }

    public string vet_name { get; set; }

    public string license_number { get; set; }

    public int? business_ID { get; set; }

    public int? department_ID { get; set; }

    public string profile { get; set; }

    public bool employment_status { get; set; }

    public int? business_img_ID { get; set; }

    public virtual business business { get; set; }

    public virtual business_img business_img { get; set; }

    public virtual department department { get; set; }

    public virtual ICollection<outpatient_clinic> outpatient_clinics { get; set; } = new List<outpatient_clinic>();
}