// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tailstale.Models;

public partial class vital_sign_record
{
    public int id { get; set; }

    public DateTime? taketime { get; set; }

    public int? HR { get; set; }

    public int? SBP { get; set; }

    public int? DBP { get; set; }

    public decimal? BT { get; set; }

    public int? RR { get; set; }

    public int? SpO2 { get; set; }

    public int? UO { get; set; }

    public string memo { get; set; }

    public int? medical_records_id { get; set; }

    public virtual medical_record medical_records { get; set; }
}